### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by TheKangaroo** [traum-ferienwohnungen/opsgenie-heartbeat-proxy#3]
Hey guys, is there an easy way to support a corporate proxy with flask/gunicorn?
I didn't do muche myself with python an a quick google search only showed me ways to use flask itself as aproxy.
Would be nice to have an easy solution to run this container behind a corporate proxy.

**Comment by jayme-github** [comment]
Hi,
you mean like an HTTP proxy for outgoing connections (to OpsGenie in this case)?
This should (haven't tried it myself) be possible via the environment variables (`HTTP_PROXY` / `HTTPS_PROXY`), see: http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by TheKangaroo** [comment]
Ah thank you @jayme-github :) I will try this in a few days an give you feedback.

**Comment by jayme-github** [comment]
Closing this for now. Please feel free to comment if this does not work out.

**Comment by TheKangaroo** [comment]
Hey, sorry for the late response.
I didn't try it anymore since there is a solution to omit the opsgenie-heartbeat-proxy and trigger the heartbeat api from alertmanager directly :)
(https://github.com/prometheus/alertmanager/pull/444#issuecomment-428493861)
